"""Unit and integration tests for ``core/evaluator.py``.

Follows strict testing guidelines:
1. Every non-trivial test specifies in its docstring the hand-verified arithmetic.
2. Explicit type assertions (``type(x) is Decimal``) to prevent float pollution.
3. Upstream integration tests use real ``Triangle`` instances generated by ``core.graph``.
"""

from decimal import Decimal
import pytest

from exchanges.base import BookTicker, TradingFees
from exchanges.fees import apply_bnb_discount
from core.graph import Triangle, TradingPair, generate_triangles
from core.evaluator import (
    evaluate_leg,
    evaluate_path,
    evaluate_triangle,
    EvaluationResult,
)


class TestEvaluateLeg:
    """Tests for individual leg rate calculations."""

    def test_buy_leg_arithmetic(self) -> None:
        """Verify BUY leg calculation for quote -> base conversion.

        Hand-verified arithmetic:
            Symbol: BTCUSDT (base: BTC, quote: USDT)
            Converting USDT -> BTC (BUY)
            Ask price: 50,000.00
            Taker fee: 0.00075 (0.075 %)
            Gross rate = 1 / 50000 = Decimal("0.00002")
            Net rate   = (1 - 0.00075) / 50000 = 0.99925 / 50000 = Decimal("0.000019985")
        """
        ticker = BookTicker(
            symbol="BTCUSDT",
            bid=Decimal("49990.00"),
            ask=Decimal("50000.00"),
            timestamp_ms=1000,
        )
        taker_fee = Decimal("0.00075")

        gross, net = evaluate_leg("USDT", "BTC", "BTCUSDT", ticker, taker_fee)

        assert type(gross) is Decimal
        assert type(net) is Decimal
        assert gross == Decimal("0.00002")
        assert net == Decimal("0.000019985")

    def test_sell_leg_arithmetic(self) -> None:
        """Verify SELL leg calculation for base -> quote conversion.

        Hand-verified arithmetic:
            Symbol: ETHUSDT (base: ETH, quote: USDT)
            Converting ETH -> USDT (SELL)
            Bid price: 2,500.00
            Taker fee: 0.00075
            Gross rate = 2,500.00 = Decimal("2500.00")
            Net rate   = 2500.00 * (1 - 0.00075) = 2500 * 0.99925 = Decimal("2498.125")
        """
        ticker = BookTicker(
            symbol="ETHUSDT",
            bid=Decimal("2500.00"),
            ask=Decimal("2501.00"),
            timestamp_ms=1000,
        )
        taker_fee = Decimal("0.00075")

        gross, net = evaluate_leg("ETH", "USDT", "ETHUSDT", ticker, taker_fee)

        assert type(gross) is Decimal
        assert type(net) is Decimal
        assert gross == Decimal("2500.00")
        assert net == Decimal("2498.125")

    def test_cross_pair_buy_leg_arithmetic(self) -> None:
        """Verify BUY leg calculation for cross pair slash-delimited symbol.

        Hand-verified arithmetic:
            Symbol: ETH/BTC (base: ETH, quote: BTC)
            Converting BTC -> ETH (BUY)
            Ask price: 0.05
            Taker fee: 0.00075
            Gross rate = 1 / 0.05 = Decimal("20")
            Net rate   = (1 - 0.00075) / 0.05 = 0.99925 / 0.05 = Decimal("19.985")
        """
        ticker = BookTicker(
            symbol="ETH/BTC",
            bid=Decimal("0.0499"),
            ask=Decimal("0.05"),
            timestamp_ms=1000,
        )
        taker_fee = Decimal("0.00075")

        gross, net = evaluate_leg("BTC", "ETH", "ETH/BTC", ticker, taker_fee)

        assert type(gross) is Decimal
        assert type(net) is Decimal
        assert gross == Decimal("20")
        assert net == Decimal("19.985")

    def test_float_type_rejection(self) -> None:
        """Verify that passing float in ticker or taker_fee raises TypeError."""
        valid_ticker = BookTicker(
            symbol="BTCUSDT",
            bid=Decimal("50000"),
            ask=Decimal("50000"),
            timestamp_ms=1000,
        )

        with pytest.raises(TypeError, match="taker_fee must be Decimal"):
            evaluate_leg("USDT", "BTC", "BTCUSDT", valid_ticker, 0.00075)  # type: ignore

        float_bid_ticker = BookTicker(
            symbol="BTCUSDT",
            bid=50000.0,  # type: ignore
            ask=Decimal("50000"),
            timestamp_ms=1000,
        )
        with pytest.raises(TypeError, match="ticker.bid must be Decimal"):
            evaluate_leg("USDT", "BTC", "BTCUSDT", float_bid_ticker, Decimal("0.00075"))


class TestEvaluatePathAndTriangle:
    """Tests for 3-leg triangle evaluation and full pipeline integration."""

    @pytest.fixture
    def setup_triangle_and_market(self):
        """Build real Triangle from core.graph and matching market tickers/fees."""
        pairs = [
            TradingPair("BTCUSDT", "BTC", "USDT", Decimal("1000000")),
            TradingPair("ETHUSDT", "ETH", "USDT", Decimal("1000000")),
            TradingPair("ETH/BTC", "ETH", "BTC", Decimal("1000000")),
        ]
        triangles = generate_triangles(pairs)
        assert len(triangles) == 1
        triangle = triangles[0]

        # Market tickers giving a profitable USDT -> BTC -> ETH -> USDT loop
        # USDT -> BTC: BUY BTC/USDT ask = 50,000
        # BTC -> ETH: BUY ETH/BTC ask = 0.05
        # ETH -> USDT: SELL ETH/USDT bid = 2,530
        tickers = {
            "BTCUSDT": BookTicker("BTCUSDT", Decimal("49990"), Decimal("50000"), 1000),
            "ETH/BTC": BookTicker("ETH/BTC", Decimal("0.0499"), Decimal("0.05"), 1000),
            "ETHUSDT": BookTicker("ETHUSDT", Decimal("2530"), Decimal("2531"), 1000),
        }

        # Nominal 0.1 % fees with BNB discount applied -> 0.075 % (0.00075)
        raw_fees = {
            s: TradingFees(s, Decimal("0.001"), Decimal("0.001"))
            for s in ("BTCUSDT", "ETH/BTC", "ETHUSDT")
        }
        discounted_fees = {s: apply_bnb_discount(f) for s, f in raw_fees.items()}

        return triangle, tickers, discounted_fees

    def test_profitable_path_hand_verified_arithmetic(self, setup_triangle_and_market) -> None:
        """Verify profitable triangle path calculations with hand-verified math.

        Hand-verified arithmetic:
            Path: USDT -> BTC -> ETH -> USDT
            Leg 1 (USDT -> BTC): ask = 50000, fee = 0.00075
                gross1 = 1 / 50000 = 0.00002
                net1 = 0.99925 / 50000 = 0.000019985
            Leg 2 (BTC -> ETH): ask = 0.05, fee = 0.00075
                gross2 = 1 / 0.05 = 20
                net2 = 0.99925 / 0.05 = 19.985
            Leg 3 (ETH -> USDT): bid = 2530, fee = 0.00075
                gross3 = 2530
                net3 = 2530 * 0.99925 = 2528.1025

            gross_return = 0.00002 * 20 * 2530 = 1.012 (Decimal("1.012"))
            net_return = 0.000019985 * 19.985 * 2528.1025 = 1.00972470732306250 (Decimal)
            total_fee_rate = 1.0 - (net_return / 1.012)
                           = 1.0 - 0.997751687078125 = 0.002248312921875

            With safety_margin = 0.0010 (0.1 %):
                1.0 + 0.0010 = 1.0010
                1.00972470732306250 > 1.0010 -> is_profitable is True
        """
        triangle, tickers, fees = setup_triangle_and_market
        safety_margin = Decimal("0.0010")

        results = evaluate_triangle(triangle, tickers, fees, safety_margin)

        assert len(results) == 2
        best = results[0]

        assert best.path == ("USDT", "BTC", "ETH", "USDT")
        assert type(best.gross_return) is Decimal
        assert type(best.net_return) is Decimal
        assert type(best.total_fee_rate) is Decimal
        assert best.gross_return == Decimal("1.012")
        assert best.net_return == Decimal("1.00972470732306250")
        assert best.total_fee_rate == Decimal("0.002248312921875")
        assert best.is_profitable is True

    def test_unprofitable_opposite_direction(self, setup_triangle_and_market) -> None:
        """Verify opposite traversal path produces net_return < 1.0.

        Hand-verified arithmetic:
            Path: USDT -> ETH -> BTC -> USDT
            Leg 1 (USDT -> ETH): ask = 2531, fee = 0.00075
                net1 = 0.99925 / 2531
            Leg 2 (ETH -> BTC): bid = 0.0499, fee = 0.00075
                net2 = 0.0499 * 0.99925
            Leg 3 (BTC -> USDT): bid = 49990, fee = 0.00075
                net3 = 49990 * 0.99925
            net_return = (0.99925 / 2531) * (0.0499 * 0.99925) * (49990 * 0.99925)
                       < 1.0
        """
        triangle, tickers, fees = setup_triangle_and_market
        safety_margin = Decimal("0.0010")

        results = evaluate_triangle(triangle, tickers, fees, safety_margin)
        worst = results[1]

        assert worst.path == ("USDT", "ETH", "BTC", "USDT")
        assert worst.net_return < Decimal("1.0")
        assert worst.is_profitable is False

    def test_safety_margin_threshold_enforcement(self, setup_triangle_and_market) -> None:
        """Verify is_profitable becomes False when net_return <= 1.0 + safety_margin."""
        triangle, tickers, fees = setup_triangle_and_market

        # With a high safety margin (e.g. 2 % = 0.0200)
        high_margin = Decimal("0.0200")
        results = evaluate_triangle(triangle, tickers, fees, high_margin)

        assert results[0].net_return == Decimal("1.00972470732306250")
        # 1.0097247... < 1.0200
        assert results[0].is_profitable is False

    def test_invalid_price_zero_return(self, setup_triangle_and_market) -> None:
        """Verify that bid/ask <= 0 produces zero return and is_profitable=False."""
        triangle, tickers, fees = setup_triangle_and_market
        zero_ticker = BookTicker("BTCUSDT", Decimal("0"), Decimal("0"), 1000)
        tickers["BTCUSDT"] = zero_ticker

        results = evaluate_triangle(triangle, tickers, fees, Decimal("0.0010"))
        for res in results:
            assert res.gross_return == Decimal("0")
            assert res.net_return == Decimal("0")
            assert res.is_profitable is False
